name: build
on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Preparing build
        run: |
          wget https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-cluster-community-java_8.0.23-1ubuntu20.10_amd64.deb
          sudo dpkg -i mysql-cluster-community-java_8.0.23-1ubuntu20.10_amd64.deb
          mvn install:install-file -DgroupId=com.mysql.ndb -DartifactId=clusterj -Dversion=8.0.23 -Dpackaging=jar -Dfile=/usr/share/mysql-8.0/java/clusterj-8.0.23.jar -DgeneratePom=true
          wget https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/ndbclient_8.0.23-1ubuntu20.10_amd64.deb
          sudo dpkg -i ndbclient_8.0.23-1ubuntu20.10_amd64.deb
          wget https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/ndbclient-dev_8.0.23-1ubuntu20.10_amd64.deb
          sudo dpkg -i ndbclient-dev_8.0.23-1ubuntu20.10_amd64.deb
          sudo ln -s /usr/lib/x86_64-linux-gnu/libndbclient.so.6.1.0 /usr/lib/x86_64-linux-gnu/libndbclient.so

      - name: Build with Maven
        run: mvn -DargLine="-Djava.library.path=/usr/lib/x86_64-linux-gnu/  @{argLine}" -B package --file pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}